version: 0.1.{build}

skip_tags: true

configuration: Release

install:
  - cinst opencover -source https://nuget.org/api/v2/
  - cinst coveralls.io -source https://nuget.org/api/v2/

branches:
  only:
  - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: IvFj1gVCvM0SPcsbwF+JFI6JOI2X/iQDu/Vp/WZTV64RjVkY/Q8OuGBkRT4OW5AQ

before_build:
  - nuget restore src\MvcMocker.sln

build:
  project: src\MvcMocker.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"\"src\MvcMocker.Test\bin\Release\MvcMocker.Test.dll\" /logger:Appveyor" -skipautoprops -filter:"+[MvcMocker*]*" -output:coverage.xml
  - coveralls.net --opencover coverage.xml

artifacts:
  - path: coverage.xml
