version: 0.1.{build}
skip_tags: true
configuration: Release
branches:
  only:
  - master
before_build:
- nuget restore src\MvcMocker.sln
build:
  project: src\MvcMocker.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal